---
- name: "upgrade and update packages."
  become: true
  become_method: sudo
  apt:
    upgrade: "yes"
    update_cache: "yes"

- name: "remove unwanted dependencies"
  become: true
  apt: 
    autoremove: "yes"

- name: "install node dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present